### ISSUE TITLE
Would it make sense to move this to the openstax org?

### ISSUE THREAD

**Issue by philschatz** [gregfitch/staxing#16]
It seems like this is being used by us & is being worked on by several people. It _seems_ like it's being used by the selenium tests (but can't tell from the name of the repository) or maybe it's just a side-project?

**Comment by philschatz** [comment]
(bump) If this is being used in https://github.com/openstax/test-automation then should it be moved to the openstax org?

**Comment by gregfitch** [comment]
Moved.
